{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-uniqtag
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/uniqtag_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/uniqtag/uniqtag_{{ version }}.tar.gz
  sha256: 25ba0731ff61857ea4c1d06c99018ed3b0d1121689b6269b79776371092fad6e

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('uniqtag')"           # [not win]
    - "\"%R%\" -e \"library('uniqtag')\""  # [win]

about:
  home: https://github.com/sjackman/uniqtag
  license: MIT
  summary: For each string in a set of strings, determine a unique tag that is a substring of fixed size k unique to that string, if it has one. If no such unique substring exists, the least frequent substring is used. If multiple unique substrings exist, the lexicographically smallest substring is used. This lexicographically
    smallest substring of size k is called the "UniqTag" of that string.
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: uniqtag
# Type: Package
# Version: 1.0
# Title: Abbreviate Strings to Short, Unique Identifiers
# Description: For each string in a set of strings, determine a unique tag that is a substring of fixed size k unique to that string, if it has one. If no such unique substring exists, the least frequent substring is used. If multiple unique substrings exist, the lexicographically smallest substring is used. This lexicographically smallest substring of size k is called the "UniqTag" of that string.
# Authors@R: person("Shaun", "Jackman", , "sjackman@gmail.com", c("cre"))
# URL: https://github.com/sjackman/uniqtag
# BugReports: https://github.com/sjackman/uniqtag/issues
# Suggests: testthat
# License: MIT + file LICENSE
# Packaged: 2015-04-28 19:20:22 UTC; sjackman
# Author: Shaun Jackman [cre]
# Maintainer: Shaun Jackman <sjackman@gmail.com>
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2015-04-29 01:17:59
