appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: H2uV5suSj5y6BYUCArJhg9vpgAHTWOC50rJTfiDF+Zqw9h71lVQhAYBc0s/XSZu2tJFIFjZDPSxxvVee0Dt48wkFuNgxgjeFgT4+Z/1/OambXENKJ5Zz3d/G4nIDmpbfNdc6lkiv+03qiKfXIxm6EouUcrDlKyiZKAXiz/mPxtCPE7ijdIeSTlfIP9tbOUKPulRbMqHJLzhLeJ5LVhrSH3zGZq5X/j9GikiiJSmhluRzPKRYJuYwbovQzW0qixTLgaz8kLa/t6EVD2ZrLcg2q4C9jjIyQKaA9+mIMvb6GrPmf48iVezQfaHcDl+iJBpv4zBhRQfD/8bIJhobEXr0RulGfFy6H1TMiUb3TKbT9uHkwz6qdcKq7M9UZygb3kdWfq1HbJoS5XZsmgOHD5stJveJB3S+LAjgj0ETAarN4a91bm5DnhtoZMP8ndHrtKZLRHI8qLBKlLCM5PLBAF3P/rIoeVZU0JWJr26I0DtjwQlkwLywbOJdiEQAj2j+kB1HXspoW9fJwImtN1EVzS1iEw+XsEVSpdF4adXOTjH1BZt9Ax112Jh7X7HiClclcueRCoNNHT0vuZl7MLrZu4dBO4AGWGGxEtwflYwEzJRhsL0/G1u/U5kl7Fo/0FuyYwa1cm/Oj7O4KrLIuLDps1P1dgMChTKzz3zovFZcELTFd/g=
conda_forge_output_validation: true
